### ISSUE TITLE
Please check the part about How To Use Docker

### ISSUE THREAD

**Issue by guoyangming-dean** [physionetchallenges/python-classifier-2022#2]
Hello, pls check part "How do I run there scrips in Docker?", as I know, the step 4(Building a Docker image and testing our code), after image build and our model training finished, we should evaluate out model using command "pyhton evaluate_model.py test_data test_outputs", but I found "model" argument exits in this command, which likely be a typo.

**Comment by matthewreyna** [comment]
Please run `python evaluate_model.py test_data test_outputs` to evaluate your model's outputs on the data.

(This command uses the word "test", but the teams do not have access to the test data, so you would use part of the training data.)
